/*This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation, version 2
  of the License.
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place - Suite 330, Boston,
  MA 02111-1307, USA.
*/
package engine.renderer;

import com.ardor3d.framework.jogl.NewtWindowContainer;
import com.ardor3d.input.jogl.JoglNewtKeyboardWrapper;
import com.jogamp.newt.event.KeyEvent;

/**
 * Keyboard wrapper that skips auto-repeat events generated by the underlying 
 * operating system
 * 
 * @author Julien Gouesse
 *
 */
public class ReliableKeyboardWrapper extends JoglNewtKeyboardWrapper{

	public ReliableKeyboardWrapper(final NewtWindowContainer newtWindowContainer){
		super(newtWindowContainer);
	}

	@Override
	public synchronized void keyPressed(final KeyEvent e){
		if(!e.isAutoRepeat())
			super.keyPressed(e);
	}
	
	@Override
	public synchronized void keyReleased(final KeyEvent e){
		if(!e.isAutoRepeat())
			super.keyReleased(e);
	}
}
